### PR TITLE
Attempt at a flatter, 2018 based theme. 

### PR DESCRIPTION
**Pull request by danleedham**
So this is not a deadly serious PR, but one to highlight that I'd like to move to a flatter, 2018 based (based on roseslive.co.uk) style. Here are a few elements. 

Feedback would be good, and I'm happy to finish it fully if people would like. 

screen shot 2018-04-10 at 20 33 09
screen shot 2018-04-10 at 20 36 38
screen shot 2018-04-10 at 20 39 07

### CODE REVIEW

**Comment by danleedham** [comment]
screen shot 2018-04-10 at 20 47 18

**Comment by peskdale** [comment]
I like the concept. Not too sure about the drop-shadow though.

If the theme were to be revised, I think this is a good opertunnity to properly standardise font and graphic sizes, as well as colour usage.

**Comment by peskdale** [comment]
Also, usage of the clock/live bugs during sports that have graphics in the top left has always been a bit wierd.

IMO, constantly showing Live and current time is very pointless - especially as it then gets baked onto the VoD.

Perhaps replace with an occational “Live from [location]” graphic in the bottom-left (a la BBC Sport)? Maybe a lower-third venue/match identer for pre-game usage.

**Comment by peskdale** [comment]
image

I think there needs to be some kind of separation between scores sharing a background colour. Tennis used above as an example, but also noticeable on Badminton, Archery, etc. Without the gradients to differentiate the lines, it looks a bit odd.

Maybe two tones of the white/gray are needed? Would be useful for lists too.

Alternatively, colour matching like this?:
image

Regarding Tennis specifically: The unplayed sets either need to be hidden properly (ng-show probably?), or need heights setting so the white blocks appear. Again, some kind separation (both horizontally and vertically) would be nice here.

**Comment by moschopsuk** [comment]
I love this new design, I'm with Peter on this I always thought having clock + live graphic was pointless. Stuff like that like from we will bake in just before encode, all disciple/sport based graphics will be done on location.

Regarding the colours what are the preferred styles for the different unis. I made the assumption when I first did this that Lancaster was red + white, and York was Gold + Black.

**Comment by stephenrob** [comment]
Live + Clock in the top left does seem pointless, especially for many sports you expect the match time / score to be there.

The new design looks great I think Red and Gold are always seen as the main colours for each university so it would be good to keep that in the graphics.

For the running score graphic @peskdale i do think the colour matching looks better than the single grey tone so maybe continuing with that else where?

**Comment by benjaminkay93** [comment]
sorted the merge conflicts, looks beautiful though :) 
I agree with @peskdale on the faded colours behind the scores 👍

**Comment by danleedham** [comment]
I'm happy to have a go at this once a few more of the functional changes have been included.

**Comment by danleedham** [comment]
Sorry. I messed up.

**Pull request closed without merging**
